### ISSUE TITLE
Responsive Teardown / Rebuild

### ISSUE THREAD

**Issue by dkemper01** [dmotz/hexaflip#12]
Hexaflip works flawlessly in a Sencha Touch 2.4.2 app I regularly maintain.  Do you have recommendations on how to destroy and recreate the hexaflip object on when a size breakpoint has been "noticed" by a resize listener?  I would like to dynamically replace images with their larger and smaller counterparts based on the horizontal width of the browser.

Thanks,

Dan

**Comment by dmotz** [comment]
My best advice if you're looking to simply replace it is to empty the containing element using `.innerHTML = ''` (or a similar approach in Sencha) and then create a new instance of HexaFlip using the same container.

You could also try using HexaFlip's `setValue` method on breakpoints, which accepts a content configuration object the same as when you create a new instance.

**Comment by dkemper01** [comment]
Yes, removing all child elements from div.hexaflip and then nullifying the existing instance and just creating a new one worked without issue.  Did not try setValue, but will follow - up with more info on using setValue when I have a chance.
