### ISSUE TITLE
Hexaflip Is Broken In Latest Chrome

### ISSUE THREAD

**Issue by artforlife** [dmotz/hexaflip#14]
My Chrome has automatically updated and the Hexaflip now looks like this. Not sure what causes it yet.

It appears that Demo1 is the only that gets broken. The other 3 demos display well.

<img width="744" alt="screen shot 2016-09-18 at 3 46 12 pm" src="https://cloud.githubusercontent.com/assets/8064423/18618553/21c76620-7db7-11e6-9a6e-8cd70c983f0f.png">

**Comment by dmotz** [comment]
The examples on Codrops are quite out of date and I don't have the ability to update them.

The latest version of the library shouldn't have this issue, but let me know if it does.

Thanks for opening.

**Comment by artforlife** [comment]
I grabbed the freshest code you have and was able to fix it. It seems that the problem had to do with how Chrome prioritizes CSS in different files, but I am not entirely sure.

As a side question, is there a nice, quick way to align the two rows of cubes in center when one word's length is not equal to the other? For instance, you have "HEXA FLIP" and each word has 4 letters. They align well on top of each other. But if you make "HEXA FLIPS" then, how could one align them in middle?

Thanks for your help.

**Comment by artforlife** [comment]
P.S. I forgot to mention that this code seems a lot faster and more optimized. Previously, when running a screen with Hexaflip, my Mac would heat up noticeably. Now it does not, even though I have the page open in 3 different browsers. Cheers to that!

**Comment by dmotz** [comment]
@artforlife Setting `text-align: center` on the outermost element should give you what you're looking for.
